name: Release Docker image (GHCR)

on:
  push:
    tags:
    - 'v*' # run only for version tags like v1.2.3
  workflow_dispatch:
  workflow_call:


permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify tag commit is on main
      id: verify
      shell: bash
      run: |
        if git branch -r --contains "$GITHUB_SHA" | grep -Eq 'origin/main$'; then
          echo "on_main=true" >> "$GITHUB_OUTPUT"
          echo "Tagged commit is on main"
        else
          echo "on_main=false" >> "$GITHUB_OUTPUT"
          echo "Tagged commit is NOT on main; subsequent steps will be skipped"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare image name (lowercase)
      id: prep
      run: |
        IMAGE="${{ env.REGISTRY }}/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
        echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
        echo "image=${IMAGE}" >> $GITHUB_OUTPUT

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      if: steps.verify.outputs.on_main == 'true'
      with:
        images: ${{ steps.prep.outputs.image }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v6
      if: steps.verify.outputs.on_main == 'true'
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        platforms: linux/amd64
        build-args: |
          XO_REF=${{ github.ref_name }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
